server:
  port: 9050
  servlet:
    context-path: /poli/v1
spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://ec2-44-193-188-118.compute-1.amazonaws.com:5432/d9ngc835lo2ptc
    username: qzcmmpgqszchjz
    password: 805c73683c03528220c8aaf4400fa975c8c4c17f1152d37f133e25ccdcf03706
    platform: postgres
  jpa:
    hibernate:
      ddl-auto: create-drop
    generate-ddl: true 





